# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TrackerGPS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TrackerGPS

#pod 'FirebaseCommunity', '~> 0.1'
pod 'Firebase/Core'

end
